// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.emails */
export type EmailsId = string & { __brand: 'EmailsId' };

/** Represents the table public.emails */
export default interface EmailsTable {
  id: ColumnType<EmailsId, EmailsId, EmailsId>;

  userId: ColumnType<UsersId, UsersId, UsersId>;

  email: ColumnType<string, string, string>;

  verified: ColumnType<boolean, boolean | undefined, boolean>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Emails = Selectable<EmailsTable>;

export type NewEmails = Insertable<EmailsTable>;

export type EmailsUpdate = Updateable<EmailsTable>;
