// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.migrations */
export type MigrationsFilename = string & { __brand: 'MigrationsFilename' };

/** Represents the table public.migrations */
export default interface MigrationsTable {
  filename: ColumnType<MigrationsFilename, MigrationsFilename, MigrationsFilename>;

  created: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Migrations = Selectable<MigrationsTable>;

export type NewMigrations = Insertable<MigrationsTable>;

export type MigrationsUpdate = Updateable<MigrationsTable>;
