// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as MigrationsTable } from './Migrations';
import type { default as UsersTable } from './Users';
import type { default as LoginsTable } from './Logins';
import type { default as EmailsTable } from './Emails';

export default interface PublicSchema {
  migrations: MigrationsTable;

  users: UsersTable;

  logins: LoginsTable;

  emails: EmailsTable;
}
