// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { EmailsId } from './Emails';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, UsersId, UsersId>;

  firstName: ColumnType<string, string, string>;

  lastName: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  primaryEmailId: ColumnType<EmailsId | null, EmailsId | null, EmailsId | null>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
